language: node_js
install:
  - npm install -g yarn
  - yarn install
script:
  - npm test
  - npm run release:semantic
env:
  global:
    - secure: k00BVlgfFnvYE/wikDY9c8HhPR/hgeB1U9cIs8rV3SNGVau1VtYsvYLAiLatO7VqE6HmITr5VxQMoOgkAeO/ATS7tXIJydlq0GMTwjtx38Vtc3/HqfuXKVVpZBahIHyNraodiGs5gl0aHZUH8pExNJl3i19aOHZXIXj6NUXNlOA=
    - secure: bbZWoSRo2838rWq/BdqUi3pMD4aXt6VdpRwNgC80GyxqS44pRvexV45bax4jfH+Cvv/IoDjQFrFalMEcDkhxfQ37EwMJB0YW1tfiUwqRZGHyKjKXoUBzOznNObxTVp7tEjra+MFKVsUKsKE80XFFgaKV6CvNbMr+qYxql+EP70M=
