[build]
  command = "npm i -g bolt && npm install deep-extend process-nextick-args util-deprecate --ignore-scripts && bolt && bolt site"
  publish = "site/public"

[context.production.environment]
  YARN_VERSION = "1.3.2"
